### ISSUE TITLE
Would you provide the negative labels

### ISSUE THREAD

**Issue by Z-ZHHH** [XueJiang16/NegLabel#1]
Thanks for sharing your great work. 
Would you provide the negative labels after NegMining? Providing negative labels of datasets like ImageNet would be much helpful, allowing for the direct utilization of the negative labels.

**Comment by XueJiang16** [comment]
Hi. We provide the scripts for dumping selected negative labels. Please refer to this commit:
https://github.com/XueJiang16/NegLabel/commit/c70279903b5d52311019356577efeea31b6b7dbf
Note that the scripts should be run with single process (GPU).
In order to facilitate the direct use of ImageNet's negative labels, we provide M=10000 selected negative labels in https://github.com/XueJiang16/NegLabel/blob/main/selected_neg_labels/selected_neg_labels_in1k_10k.txt.

**Comment by Z-ZHHH** [comment]
Tanks for your detailed reply!
